"""Add is_manager column to user table

Revision ID: cba5b58c6cd4
Revises: d0f4b38c0c84
Create Date: 2024-10-09 02:06:34.689445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cba5b58c6cd4'
down_revision = 'd0f4b38c0c84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_manager', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_manager')

    # ### end Alembic commands ###
